[package]
name = "redis-with-rust-example"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio ={ version = "1.48.0", features = ["full"] }
redis = { version = "0.32.7", features = ["tokio-native-tls-comp", "connection-manager"] }
serde = { version = "1.0.228", features = ["derive"] }
